version: '3.1'
services:

  myfarm:
    build: .
    container_name: myfarm
    ports:
      - "18080:8080"
      - "18787:8787"
    restart: always
    depends_on:
      - postgresqldb

  postgresqldb:
    image: postgres:10.7
    container_name: postgresqldb
    environment:
      - POSTGRES_USER=siva
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=appdb
    ports:
      - "5432:5432"
